version: '3.8'

services:

  postgresdb:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chirpAPi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dotnet_app
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword
    ports:
      - "5000:80"